name: run_changes

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the main branch
on:
  workflow_dispatch:      

env:
    LIQUIBASE_PRO_LICENSE_KEY: ${{ secrets.LB_PROKEY }}
    LIQUIBASE_COMMAND_URL: ${{ secrets.LB_URL }}
    LIQUIBASE_COMMAND_USERNAME: ${{ secrets.LB_USER }}
    LIQUIBASE_COMMAND_PASSWORD: ${{ secrets.LB_PASSWORD }}
    LIQUIBASE_DRIVER: ${{ secrets.LB_DRIVER }}
    
#     LIQUIBASE_COMMAND_CHANGELOG_FILE: ${{ secrets.LIQUIBASE_COMMAND_CHANGELOG_FILE }}
    
jobs:

  Build_Job:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Running Quality Checks
      uses: docker://liquibase/liquibase:4.8.0
      with:
        args: --changeLogFile=Changelogs/cyclopsbi.xml checks run

    - name: Running Status
      uses: docker://liquibase/liquibase:4.8.0
      with:
        args: --changeLogFile=Changelogs/cyclopsbi.xml status --verbose
