name: rollback_changes

on:
  workflow_dispatch:      
    inputs:
      numChangesets:
        description: 'Number of Changesets to Roll Back'
        required: false
        default: '0'

env:
    LIQUIBASE_PRO_LICENSE_KEY: ${{ secrets.LB_PROKEY }}
    LIQUIBASE_COMMAND_URL: ${{ secrets.LB_URL }}
    LIQUIBASE_COMMAND_USERNAME: ${{ secrets.LB_USER }}
    LIQUIBASE_COMMAND_PASSWORD: ${{ secrets.LB_PASSWORD }}
    LIQUIBASE_DRIVER: ${{ secrets.LB_DRIVER }}
    
#     LIQUIBASE_COMMAND_CHANGELOG_FILE: ${{ secrets.LIQUIBASE_COMMAND_CHANGELOG_FILE }}
    
jobs:

  Build_Job:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Running Quality Checks
      uses: docker://liquibase/liquibase:4.8.0
      with:
        args: --changeLogFile=Changelogs/cyclopsbi.xml rollbackCount ${{ github.event.inputs.numChangesets }}
